const COMMANDS: Record<string, string[]> = {
  init: ["--name", "--dir", "--copy-scripts", "--non-interactive"],
  "setup-agents": ["--dir", "--dry-run", "--cron", "--uninstall"],
  start: ["--dir"],
  stop: ["--dir"],
  pause: ["--dir"],
  resume: ["--dir"],
  status: ["--dir", "--json", "--quiet"],
  doctor: ["--dir", "--fix"],
  logs: ["--dir", "--id", "--tail", "--follow"],
  version: [],
  "add-task": ["--tag", "--description", "--position", "--dir"],
  run: ["--agent", "--gate", "--worker", "--dir"],
  dashboard: ["--port"],
  "reset-task": ["--dir", "--force"],
  cleanup: ["--dir", "--force"],
  watch: ["--dir"],
  upgrade: ["--check"],
  metrics: ["--dir"],
  export: ["--dir", "--output"],
  import: ["--dir", "--dry-run", "--merge", "--force"],
  config: ["--dir"],
  completions: [],
  "test-notify": ["--channel", "--dir"],
};

const COMMAND_NAMES = Object.keys(COMMANDS).join(" ");

function generateBash(): string {
  const flagCases = Object.entries(COMMANDS)
    .filter(([, flags]) => flags.length > 0)
    .map(([cmd, flags]) => `      ${cmd}) opts="${flags.join(" ")}" ;;`)
    .join("\n");

  return `# skynet bash completions
# Generated by: skynet completions bash
_skynet() {
  local cur prev cmd opts
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  # Find the subcommand
  cmd=""
  for ((i=1; i < COMP_CWORD; i++)); do
    case "\${COMP_WORDS[i]}" in
      -*) ;;
      *) cmd="\${COMP_WORDS[i]}"; break ;;
    esac
  done

  # Complete subcommands
  if [ -z "$cmd" ]; then
    COMPREPLY=( $(compgen -W "${COMMAND_NAMES}" -- "$cur") )
    return 0
  fi

  # Complete flags per subcommand
  opts=""
  case "$cmd" in
${flagCases}
  esac

  COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
  return 0
}

complete -F _skynet skynet`;
}

function generateZsh(): string {
  const commandEntries = Object.entries(COMMANDS)
    .map(([cmd, flags]) => {
      const flagArgs = flags
        .map((f) => `'${f}[${f.replace(/^--/, "")}]'`)
        .join(" ");
      if (flagArgs) {
        return `      ${cmd}) _arguments ${flagArgs} ;;`;
      }
      return `      ${cmd}) ;;`;
    })
    .join("\n");

  return `#compdef skynet
# skynet zsh completions
# Generated by: skynet completions zsh

_skynet() {
  local -a commands
  commands=(
    'init:Initialize Skynet pipeline in the current project'
    'setup-agents:Install scheduled agents (launchd on macOS, cron on Linux)'
    'start:Start the Skynet pipeline'
    'stop:Stop all running Skynet workers'
    'pause:Pause the Skynet pipeline'
    'resume:Resume a paused Skynet pipeline'
    'status:Show pipeline status summary'
    'doctor:Run diagnostics on the Skynet pipeline'
    'logs:View pipeline log files'
    'version:Show CLI version and check for updates'
    'add-task:Add a new task to the backlog'
    'run:Run a single task one-shot'
    'dashboard:Launch the Skynet admin dashboard'
    'reset-task:Reset a failed task back to pending'
    'cleanup:Clean up merged and orphaned branches'
    'watch:Real-time terminal dashboard'
    'upgrade:Upgrade skynet-cli to the latest version'
    'metrics:Show pipeline performance analytics'
    'export:Export pipeline state as a JSON snapshot'
    'import:Restore pipeline state from a JSON snapshot'
    'config:View and edit pipeline configuration'
    'completions:Generate shell completions'
    'test-notify:Test notification channels'
  )

  _arguments -C \\
    '1:command:->cmd' \\
    '*::arg:->args'

  case "$state" in
    cmd)
      _describe -t commands 'skynet command' commands
      ;;
    args)
      case "$words[1]" in
${commandEntries}
      esac
      ;;
  esac
}

_skynet "$@"`;
}

export async function completionsCommand(shell: string) {
  switch (shell) {
    case "bash":
      console.error(
        '# Add to ~/.bashrc:\n#   eval "$(skynet completions bash)"'
      );
      console.log(generateBash());
      break;
    case "zsh":
      console.error(
        '# Add to ~/.zshrc:\n#   eval "$(skynet completions zsh)"'
      );
      console.log(generateZsh());
      break;
    default:
      console.error(
        `Unknown shell: ${shell}. Supported shells: bash, zsh`
      );
      process.exit(1);
  }
}
