#!/usr/bin/env bash
# skynet.config.sh — Machine-specific pipeline configuration
# Generated by: npx skynet init
# This file should be in .gitignore (it contains local paths and secrets)

# ---- Project Identity ----
export SKYNET_PROJECT_NAME="PLACEHOLDER_PROJECT_NAME"
export SKYNET_PROJECT_DIR="PLACEHOLDER_PROJECT_DIR"
export SKYNET_DEV_DIR="$SKYNET_PROJECT_DIR/.dev"

# ---- Lock Files (auto-derived from project name) ----
export SKYNET_LOCK_PREFIX="/tmp/skynet-${SKYNET_PROJECT_NAME}"

# ---- Dev Server ----
export SKYNET_DEV_SERVER_CMD="pnpm dev"
export SKYNET_DEV_SERVER_URL="http://localhost:3000"
export SKYNET_DEV_SERVER_PORT=3000

# ---- Build & Test Commands ----
export SKYNET_TYPECHECK_CMD="pnpm typecheck"
export SKYNET_LINT_CMD="pnpm lint"

# ---- Quality Gates (run in order before merge) ----
# Define quality gates as numbered SKYNET_GATE_N variables.
# Each gate is a command run from the worktree directory.
# If any gate fails, the branch is NOT merged.
# Default: just typecheck (SKYNET_GATE_1 falls back to SKYNET_TYPECHECK_CMD)
export SKYNET_GATE_1="pnpm typecheck"
# export SKYNET_GATE_2="pnpm lint"
# export SKYNET_GATE_3="npx playwright test e2e/smoke.spec.ts --reporter=list"

# ---- Playwright (leave empty to skip tests) ----
export SKYNET_PLAYWRIGHT_DIR=""
export SKYNET_SMOKE_TEST="e2e/smoke.spec.ts"
export SKYNET_FEATURE_TEST="e2e/features.spec.ts"

# ---- Git ----
export SKYNET_BRANCH_PREFIX="dev/"
export SKYNET_MAIN_BRANCH="main"

# ---- Worker Tuning ----
export SKYNET_MAX_WORKERS=2
export SKYNET_MAX_TASKS_PER_RUN=5
export SKYNET_STALE_MINUTES=45
export SKYNET_MAX_FIX_ATTEMPTS=3

# ---- Auth (Claude Code OAuth) ----
export SKYNET_AUTH_TOKEN_CACHE="/tmp/skynet-${SKYNET_PROJECT_NAME}-claude-token"
export SKYNET_AUTH_FAIL_FLAG="/tmp/skynet-${SKYNET_PROJECT_NAME}-auth-failed"
export SKYNET_AUTH_KEYCHAIN_SERVICE="Claude Code-credentials"
export SKYNET_AUTH_KEYCHAIN_ACCOUNT="${USER}"
export SKYNET_AUTH_NOTIFY_INTERVAL=3600

# ---- Notifications (Telegram) ----
# Leave empty to disable Telegram notifications
export SKYNET_TG_ENABLED=false
export SKYNET_TG_BOT_TOKEN=""
export SKYNET_TG_CHAT_ID=""

# ---- Claude Code ----
export SKYNET_CLAUDE_BIN="claude"
export SKYNET_CLAUDE_FLAGS="--print --dangerously-skip-permissions"

# ---- Codex CLI (OpenAI fallback) ----
export SKYNET_CODEX_BIN="codex"
export SKYNET_CODEX_FLAGS="--full-auto"
export SKYNET_AGENT_PREFERENCE="auto"  # claude | codex | auto

# ---- Environment ----
export SKYNET_EXTRA_PATH="/opt/homebrew/bin:/usr/local/bin"

# ---- Server Error Scanning ----
# Space-separated list of env vars to check in server logs
export SKYNET_ERROR_ENV_KEYS=""
